FROM node:latest

# Set working directory.
RUN mkdir /usr/src/app
WORKDIR /usr/src

COPY index.js /usr/src/app/index.js
COPY lib /usr/src/app/lib

# Install and cache dependencies.
COPY package.json /usr/src/package.json
COPY package-lock.json /usr/src/package-lock.json
RUN npm install --no-progress

CMD ["npm", "start"]